"""Add Student Course relationship

Revision ID: 614ea3b8dfbe
Revises: 579ed7677d6a
Create Date: 2024-06-26 15:58:49.888712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '614ea3b8dfbe'
down_revision = '579ed7677d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('passmark', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_course',
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('fk_student_course_course_id_course')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_student_course_student_id_students'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_course')
    op.drop_table('course')
    # ### end Alembic commands ###
