"""Add Email field top Students Table

Revision ID: f0e7fd04348c
Revises: 6e5bc44d2bfe
Create Date: 2024-06-25 09:40:07.313262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0e7fd04348c'
down_revision = '6e5bc44d2bfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
